# Generated by Django 5.1.7 on 2025-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstyle',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='desc_group',
            field=models.TextField(unique=True),
        ),
    ]
