# Generated by Django 5.1.7 on 2025-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0002_customstyle_imagen_alter_group_desc_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstyle',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
