# Generated by Django 5.1.7 on 2025-04-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0003_customstyle_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstyle',
            name='title',
        ),
    ]
