# Generated by Django 5.1.7 on 2025-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0004_remove_customstyle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
