# Generated by Django 5.1.7 on 2025-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0005_alter_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='password',
            field=models.TextField(default='1234'),
        ),
        migrations.AddField(
            model_name='connection',
            name='table',
            field=models.TextField(default='abcd'),
        ),
        migrations.AddField(
            model_name='connection',
            name='token',
            field=models.CharField(default='74f9ac9f-d441-4e33-af1c-8059bc4e1ceb', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='host',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.TextField(),
        ),
    ]
