# Generated by Django 5.1.7 on 2025-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0006_connection_password_connection_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='table',
        ),
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='5006d2ae-9406-4e2a-8b90-435306b5a377', max_length=50, unique=True),
        ),
    ]
