# Generated by Django 5.1.7 on 2025-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0007_remove_connection_table_alter_connection_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='db_name',
            field=models.TextField(default='abcd'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='15bcc65a-52b9-412f-8d72-7803615730cf', max_length=50, unique=True),
        ),
    ]
