# Generated by Django 5.1.7 on 2025-04-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0008_connection_db_name_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='3cda68fc-7725-4b6d-bfa3-c791e74adbd3', max_length=50, unique=True),
        ),
    ]
