# Generated by Django 5.1.7 on 2025-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0009_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='9ba52bf2-5f22-45aa-b73b-8196cb9fef50', max_length=50, unique=True),
        ),
    ]
