# Generated by Django 5.2 on 2025-05-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0010_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='db_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='76e33593-cc3a-46be-99aa-7112ca1881f3', max_length=50, unique=True),
        ),
    ]
