# Generated by Django 5.2 on 2025-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0011_alter_connection_db_type_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='db_type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='bf239d86-ea08-45b0-ada3-ddf25f317f46', max_length=256, unique=True),
        ),
    ]
