# Generated by Django 5.0.14 on 2025-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0012_alter_connection_db_type_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='6ade95e2-b68c-4c64-9d39-78c3c0d92815', max_length=256, unique=True),
        ),
    ]
