# Generated by Django 5.0.14 on 2025-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0013_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='16da5090-afef-437c-9691-1bcd91b78cf1', max_length=256, unique=True),
        ),
    ]
