# Generated by Django 5.0.14 on 2025-05-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0014_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='32b30a4f-e9e0-4823-b2cb-9fafa6b36cd7', max_length=256, unique=True),
        ),
    ]
