# Generated by Django 5.0.14 on 2025-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0015_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='c48891d3-6a48-49c5-a23d-70ebcca98661', max_length=256, unique=True),
        ),
    ]
