# Generated by Django 5.0.14 on 2025-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0016_alter_connection_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='token',
            field=models.CharField(default='cc8e647c-8453-4bb3-acad-b98a767ba55f', max_length=256, unique=True),
        ),
    ]
