version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn GestorDDBB.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
    environment:
      DJANGO_PORT: ${DJANGO_PORT}
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
